In [36]:
import pandas as pd

In [45]:
df = pd.read_csv('Loughran-McDonald_10X_Summaries_1993-2021.csv')

In [46]:
df

,CIK,FILING_DATE,ACC_NUM,CPR,FORM_TYPE,CoName,SIC,FFInd,N_Words,N_Unique_Words,...,N_WeakModal,N_Constraining,N_Negation,GrossFileSize,NetFileSize,NonTextDocTypeChars,HTMLChars,XBRLChars,XMLChars,N_Exhibits
0,60512,19930813,0000060512-94-000005,19930630,10-Q,LOUISIANA LAND & EXPLORATION CO,1311,30,4068,770,...,6,8,1,63255,43072,0,464,0,0,0
1,66740,19930813,0000066740-94-000015,19930630,10-Q,MINNESOTA MINING & MANUFACTURING CO,2670,38,4389,844,...,7,8,3,57283,37946,0,392,0,0,3
2,60512,19931007,0000060512-94-000006,19921231,10-K-A,LOUISIANA LAND & EXPLORATION CO,1311,30,8719,1239,...,15,32,5,114136,86058,0,944,0,0,0
3,60512,19931110,0000060512-94-000007,19930930,10-Q,LOUISIANA LAND & EXPLORATION CO,1311,30,4938,812,...,4,5,1,72062,50742,0,505,0,0,0
4,11860,19931112,0000011860-94-000005,19930930,10-Q,BETHLEHEM STEEL CORP /DE/,3312,19,3823,898,...,5,32,2,40392,32088,0,201,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140481,1317839,20211230,0001477932-21-009563,20210930,10-Q,Umatrin Holding Ltd,7389,34,4795,898,...,11,19,7,4180291,38642,641880,1084579,936212,1361281,7
1140482,1796160,20211230,0001096906-21-003094,20210930,10-Q,QMIS TBS Capital Group Corp.,6211,47,8028,1083,...,24,36,6,3537544,62494,516984,1121439,797163,949861,9
1140483,1867956,20211230,0001683168-21-006658,20211130,10-Q,Linktory Inc.,7370,34,3673,706,...,9,28,4,1320557,28483,319756,226958,315552,406289,8
1140484,1879373,20211230,0001493152-21-032779,20210930,10-Q,Energem Corp,6770,47,8586,1037,...,47,49,5,2260634,61730,447872,478735,609559,626915,9
1140485,711377,20211230,0001193125-21-370461,20211130,10-Q,NEOGEN CORP,2835,13,9060,1310,...,13,32,5,5341731,69643,777296,1893797,1234263,1179257,8

In [48]:
# This code extracts only top 10 companies' 10-K meta data listed in QQQ ETF from 2007 to 2021

company_name = ["Apple Inc.", "APPLE INC", "APPLE COMPUTER INC", "MICROSOFT CORP", "AMAZON COM INC", "AMAZON SCIENTIFIC INC", "AMAZON BIOTECH INC", "NVIDIA CORP/CA", "NVIDIA CORP", "Facebook Inc", "Broadcom Inc.", "Broadcom Ltd", "Broadcom Cayman L.P", "Tesla  Inc.", "TESLA MOTORS INC", "Alphabet Holding Company  Inc.", "Alphabet Inc.", "COSTCO WHOLESALE CORP", "COSTCO WHOLESALE CORP /NEW"]

df = df[df['CoName'].isin([name for name in company_name])]
# Assuming df is your DataFrame
# Convert the FILING_DATE column to datetime if it's not already
df['FILING_DATE'] = pd.to_datetime(df['FILING_DATE'], format='%Y%m%d', errors='coerce')

# Define the date range
start_date = pd.Timestamp('2007-01-01')
end_date = pd.Timestamp('2021-12-31')

# Apply the date range filter
df = df[(df['FILING_DATE'] >= start_date) & (df['FILING_DATE'] <= end_date)]

# Filter by FORM_TYPE
filtered_df = df[df['FORM_TYPE'] == '10-K']
filtered_df

,CIK,FILING_DATE,ACC_NUM,CPR,FORM_TYPE,CoName,SIC,FFInd,N_Words,N_Unique_Words,...,N_WeakModal,N_Constraining,N_Negation,GrossFileSize,NetFileSize,NonTextDocTypeChars,HTMLChars,XBRLChars,XMLChars,N_Exhibits
617197,1018724,2007-02-16,0001193125-07-034081,20061231,10-K,AMAZON COM INC,5961,42,35109,2651,...,202,266,7,1391808,278435,0,971002,0,0,7
620976,1045810,2007-03-16,0001045810-07-000008,20070128,10-K,NVIDIA CORP,3674,36,52696,3048,...,383,295,23,3464591,417798,128611,2266999,0,0,6
641151,789019,2007-08-03,0001193125-07-170817,20070630,10-K,MICROSOFT CORP,7372,34,45232,3255,...,262,260,26,1255569,348085,0,785803,0,0,8
651818,909832,2007-10-25,0001193125-07-225805,20070902,10-K,COSTCO WHOLESALE CORP /NEW,5331,42,29980,2414,...,117,168,15,1124434,249235,0,761447,0,0,4
659377,320193,2007-11-15,0001047469-07-009340,20070929,10-K,APPLE INC,3571,35,68140,3999,...,357,381,45,1178091,514449,32903,516925,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113794,1045810,2021-02-26,0001045810-21-000010,20210131,10-K,NVIDIA CORP,3674,36,37690,3327,...,347,261,20,11996719,284291,2031891,4086691,2912048,2476768,12
1126542,789019,2021-07-29,0001564590-21-039151,20210630,10-K,MICROSOFT CORP,7372,34,38889,3407,...,343,277,13,26907098,294830,1868739,8495162,3351034,12018491,11
1133154,909832,2021-10-06,0000909832-21-000014,20210829,10-K,COSTCO WHOLESALE CORP /NEW,5331,42,22276,2410,...,184,138,9,8909523,170291,1578626,2837376,2169037,2009688,9
1133990,320193,2021-10-29,0000320193-21-000105,20210925,10-K,Apple Inc.,3571,35,36041,2852,...,262,336,29,10502096,265156,1924686,3415839,2534044,2179848,11
1140200,1730168,2021-12-17,0001730168-21-000153,20211031,10-K,Broadcom Inc.,3674,36,47693,3425,...,538,417,21,16778182,359984,2376877,5896173,4183001,3661843,11

In [49]:
files_num = filtered_df['ACC_NUM'].tolist()
files_num

['0001193125-07-034081',
 '0001045810-07-000008',
 '0001193125-07-170817',
 '0001193125-07-225805',
 '0001047469-07-009340',
 '0001193125-08-024707',
 '0001045810-08-000011',
 '0001193125-08-162768',
 '0001193125-08-211709',
 '0001193125-08-224958',
 '0001193125-09-014406',
 '0001045810-09-000013',
 '0001193125-09-158735',
 '0001193125-09-208963',
 '0001193125-09-214859',
 '0001193125-10-016098',
 '0001045810-10-000006',
 '0001193125-10-171791',
 '0001193125-10-230379',
 '0001193125-10-238044',
 '0001193125-11-016253',
 '0001193125-11-054847',
 '0001045810-11-000015',
 '0001193125-11-200680',
 '0001193125-11-271844',
 '0001193125-11-282113',
 '0001193125-12-032846',
 '0001193125-12-081990',
 '0001045810-12-000013',
 '0001193125-12-316848',
 '0001193125-12-428890',
 '0001193125-12-444068',
 '0001193125-13-028520',
 '0001326801-13-000003',
 '0001193125-13-096241',
 '0001045810-13-000008',
 '0001193125-13-310206',
 '0001445305-13-002422',
 '0001193125-13-416534',
 '0001047469-13-010853',
 '0001018724-14-000006',
 '0001326801-14-000007',
 '0001193125-14-069681',
 '0001045810-14-000030',
 '0001193125-14-289961',
 '0000909832-14-000021',
 '0001193125-14-383437',
 '0001047469-14-009533',
 '0001326801-15-000006',
 '0001018724-15-000006',
 '0001564590-15-001031',
 '0001045810-15-000036',
 '0001193125-15-272806',
 '0000909832-15-000014',
 '0001193125-15-356351',
 '0001047469-15-008749',
 '0001326801-16-000043',
 '0001018724-16-000172',
 '0001652044-16-000012',
 '0001652044-16-000012',
 '0001564590-16-013195',
 '0001045810-16-000205',
 '0001193125-16-662209',
 '0000909832-16-000032',
 '0001628280-16-020309',
 '0001649338-16-000151',
 '0001326801-17-000007',
 '0001652044-17-000008',
 '0001018724-17-000011',
 '0001045810-17-000027',
 '0001564590-17-003118',
 '0001564590-17-014900',
 '0000909832-17-000014',
 '0000320193-17-000070',
 '0001649338-17-000158',
 '0001649338-17-000158',
 '0001326801-18-000009',
 '0001018724-18-000005',
 '0001652044-18-000007',
 '0001564590-18-002956',
 '0001045810-18-000010',
 '0001564590-18-019062',
 '0000909832-18-000013',
 '0000320193-18-000145',
 '0001730168-18-000084',
 '0001326801-19-000009',
 '0001018724-19-000004',
 '0001652044-19-000004',
 '0001564590-19-003165',
 '0001045810-19-000023',
 '0001564590-19-027952',
 '0000909832-19-000019',
 '0000320193-19-000119',
 '0001730168-19-000144',
 '0001326801-20-000013',
 '0001018724-20-000004',
 '0001652044-20-000008',
 '0001564590-20-004475',
 '0001045810-20-000010',
 '0001564590-20-034944',
 '0000909832-20-000017',
 '0000320193-20-000096',
 '0001730168-20-000226',
 '0001326801-21-000014',
 '0001018724-21-000004',
 '0001652044-21-000010',
 '0001564590-21-004599',
 '0001045810-21-000010',
 '0001564590-21-039151',
 '0000909832-21-000014',
 '0000320193-21-000105',
 '0001730168-21-000153']

In [29]:
# Convert the 'CoName' column to a list
company_names = set(df['CoName'])
# Open a text file for writing
with open('company_names.txt', 'w') as file:
    for name in company_names:
        file.write(name + '\n')

print("Company names have been written to company_names.txt")

Company names have been written to company_names.txt