In [1]:
import pandas as pd

In [7]:
file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10Q/dtm_SP500_10q/part-00000-303b5bef-fd1d-45e3-898d-842efa4553b0-c000.snappy.parquet"

# Read a Parquet file
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
df.head(1340)

(1394, 9170)

,Date,_cik,_vol,_ret,_vol+1,_ret+1,united,state,security,exchange,...,graduating,tal,subside,athletic,nonmaterial,storytelling,sociopolitical,shaping,wordle,newsletter
0,2011-10-27 23:00:00,0001060391,0.000068,-0.012749,0.000225,0.012570,7.0,19.0,33.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2012-04-26 23:00:00,0001060391,0.000010,0.008286,0.000174,-0.001463,7.0,20.0,34.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2012-07-26 23:00:00,0001060391,0.000037,-0.029640,0.000091,-0.013395,7.0,28.0,30.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2012-11-02 00:00:00,0001060391,0.000024,-0.003681,0.000236,-0.016145,7.0,41.0,30.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2013-04-25 23:00:00,0001060391,0.000169,-0.031417,0.000171,0.002669,6.0,35.0,30.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,2018-04-30 23:00:00,0000200406,0.000127,0.045732,0.000206,0.016224,152.0,181.0,53.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1336,2018-08-01 23:00:00,0000200406,0.000079,-0.003976,0.000067,-0.005853,158.0,187.0,57.0,41.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1337,2018-10-31 00:00:00,0000200406,0.000100,-0.041831,0.000055,-0.005340,166.0,198.0,58.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1338,2019-04-30 23:00:00,0000200406,0.000113,0.025215,0.000075,0.004449,196.0,230.0,50.0,43.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1339,2019-07-28 23:00:00,0000200406,0.000123,-0.024944,0.000031,0.002948,198.0,232.0,54.0,52.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10K/dtm_SP500_test/part-00000-8d1a78ed-23d1-428d-85ad-7d7bb97375a2-c000.snappy.parquet"
# Read a Parquet file
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
print(set(df["_cik"]))
print(len(set(df["_cik"])))
print(df['_cik'][df["_cik"] == "0000036270"])
print(len(df['_cik'][df["_cik"] == "0000036270"]))
df.head(300)

(891, 13070)
{'0000030625', '0000006281', '0000036104', '0000023217', '0000033185', '0000021344', '0000029989', '0000010456', '0000006951', '0000028917', '0000008818', '0000004127', '0000004904', '0000010795', '0000002969', '0000031462', '0000021076', '0000021665', '0000005272', '0000035527', '0000029534', '0000027419', '0000001800', '0000014930', '0000012659', '0000024741', '0000029905', '0000011544', '0000014272', '0000034903', '0000016732', '0000027904', '0000004962', '0000030697', '0000028412', '0000012208', '0000018230', '0000012927', '0000004977', '0000016918', '0000020286', '0000002488', '0000018349', '0000032604', '0000033213', '0000007084', '0000006201', '0000036270', '0000005513', '0000034088'}
50
287    0000036270
288    0000036270
289    0000036270
290    0000036270
291    0000036270
292    0000036270
293    0000036270
294    0000036270
295    0000036270
296    0000036270
297    0000036270
298    0000036270
299    0000036270
300    0000036270
301    0000036270
302    0000036270
303    0000036270
304    0000036270
Name: _cik, dtype: object
18

,Date,_cik,_vol,_ret,_vol+1,_ret+1,f,security,exchange,commission,...,reconnection,peggy,meditation,breaker,fowler,endless,connectedness,unproven,filterable,unreasoned
0,2006-09-10 23:00:00,0000007084,0.000138,0.013380,0.000705,0.024975,2.0,32.0,34.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2007-08-26 23:00:00,0000007084,0.000068,-0.005282,0.000173,0.012080,2.0,117.0,74.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2008-08-28 23:00:00,0000007084,0.000150,-0.012606,0.000263,0.024193,2.0,125.0,65.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2009-08-25 23:00:00,0000007084,0.000232,-0.054978,0.000246,-0.016441,2.0,133.0,67.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010-08-29 23:00:00,0000007084,0.000097,-0.002192,0.000121,-0.009457,4.0,110.0,63.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,2014-02-21 00:00:00,0000036270,0.000172,0.000685,0.000173,-0.013229,0.0,519.0,56.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
296,2015-02-20 00:00:00,0000036270,0.000285,-0.039180,0.000023,-0.001238,0.0,497.0,53.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
297,2016-02-19 00:00:00,0000036270,0.000095,0.021141,0.000052,-0.009179,1.0,474.0,54.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
298,2017-02-22 00:00:00,0000036270,0.000191,-0.005940,0.000092,-0.008458,10.0,431.0,48.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299,2018-02-22 00:00:00,0000036270,0.000101,-0.026023,0.000133,-0.016938,9.0,415.0,56.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:

file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10K/dtm_SP500_test/part-00000-8d1a78ed-23d1-428d-85ad-7d7bb97375a2-c000.snappy.parquet"
# Read a Parquet file
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
print(set(df["_cik"]))
print(len(set(df["_cik"])))
print(df['_cik'][df["_cik"] == "0000036270"])

df.head(300)

(18, 3428)
{'0000036270'}
1
0     0000036270
1     0000036270
2     0000036270
3     0000036270
4     0000036270
5     0000036270
6     0000036270
7     0000036270
8     0000036270
9     0000036270
10    0000036270
11    0000036270
12    0000036270
13    0000036270
14    0000036270
15    0000036270
16    0000036270
17    0000036270
Name: _cik, dtype: object

,Date,_cik,_vol,_ret,_vol+1,_ret+1,bank,corporation,heading,united,...,car,renewable,universal,certify,questionnaire,white,purport,reinvest,recoupment,st
0,2006-02-28,0000036270,0.000054,0.003552,0.000013,-0.001239,504.0,98.0,1002.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2007-02-23,0000036270,0.000081,0.006102,0.000046,0.004861,498.0,93.0,1031.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2008-02-21,0000036270,0.000509,0.029929,0.000831,-0.019642,534.0,95.0,1093.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2009-02-23,0000036270,0.002454,0.007334,0.007074,-0.096980,524.0,93.0,1164.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010-02-19,0000036270,0.000126,-0.016188,0.000106,-0.013018,484.0,88.0,1340.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2011-02-22,0000036270,0.000128,0.003120,0.000126,0.005820,482.0,86.0,1466.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2012-02-23,0000036270,0.000173,-0.016207,0.000070,0.004636,441.0,102.0,1459.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2013-02-25,0000036270,0.000490,0.032549,0.000096,0.001958,420.0,102.0,1527.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2014-02-21,0000036270,0.000065,-0.009916,0.000173,-0.013229,427.0,113.0,1286.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2015-02-20,0000036270,0.000115,-0.005040,0.000023,-0.001238,420.0,94.0,1321.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2016-02-19,0000036270,0.000203,-0.012407,0.000052,-0.009179,416.0,99.0,1276.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2017-02-22,0000036270,0.000047,-0.006868,0.000092,-0.008458,410.0,90.0,1643.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2018-02-22,0000036270,0.000315,0.024191,0.000133,-0.016938,392.0,90.0,1578.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2019-02-20,0000036270,0.000164,-0.014998,0.000093,0.008801,375.0,69.0,1563.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2020-02-20,0000036270,0.000092,-0.011271,0.000036,-0.000653,353.0,68.0,1598.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2021-02-22,0000036270,0.000764,-0.038137,0.000587,-0.013582,381.0,77.0,1611.0,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2022-02-16,0000036270,0.000222,-0.021673,0.000113,0.009643,382.0,77.0,1612.0,77.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2023-02-22,0000036270,0.000115,0.011606,0.000124,0.006250,394.0,71.0,1556.0,175.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:

file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10K/dtm_SP500_test/part-00000-6897efa1-19dd-4ee8-b5b0-9c199b8fffa2-c000.snappy.parquet"
# Read a Parquet file
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
# print(set(df["_cik"]))
# print(len(set(df["_cik"])))
# print(df['_cik'][df["_cik"] == "0000036270"])

# df.head(300)

(900, 13433)

In [18]:

file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10K/dtm_SP500_test3/part-00000-abf94af4-2693-4aab-bfc9-1344baa82171-c000.snappy.parquet"
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)

(142, 10459)

In [19]:
import os
import pandas as pd

In [27]:
save_path = "/Users/apple/PROJECT/hons_project/data/SP500/10K"
existing_files_path = os.path.join(save_path, 'processed')
existing_files = os.listdir(existing_files_path)
existing_files = [f for f in existing_files if f != '.DS_Store']
existing_files = [os.path.join(existing_files_path, f) for f in existing_files]
batch_size=50

def chunker(seq, size):
            for pos in range(0, len(seq), size):
                yield seq[pos:pos + size]
for chunk_index, chunk in enumerate(chunker(existing_files, batch_size)):
    print(chunk_index)
    for file_path in chunk:
        print(file_path)
        table = pd.read_table(file_path)

0
/Users/apple/PROJECT/hons_project/data/SP500/10K/processed/dtm_0001467858.parquet

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 7: invalid continuation byte

In [52]:

file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10Q/intermediate/batch_0.parquet"
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
print(df["Date"])
# df.head()

(1839, 10315)
0      2012-05-03
1      2012-08-03
2      2012-10-31
3      2013-05-02
4      2013-07-25
          ...
1834   2022-09-13
1835   2022-12-13
1836   2023-03-10
1837   2023-09-12
1838   2023-12-12
Name: Date, Length: 1839, dtype: datetime64[ns]

In [43]:
def convert_timestamps_to_strings(df, path):
    # Convert timestamp columns to strings
    for col in df.select_dtypes(include=['datetime64[ns]']).columns:
        df[col] = df[col].astype(str)
    df = df.drop(df.columns[0], axis=1)
    df.to_parquet(path, index=False)
    return df

In [45]:
save_path = "/Users/apple/PROJECT/hons_project/data/SP500/10K"
# save_path = os.path.join(save_path, 'intermediate')
df_converted = convert_timestamps_to_strings(df, 'output_file.parquet')
print(df_converted["Date"])
df_converted

0     2006-03-16
1     2007-03-16
2     2009-03-13
3     2010-03-18
4     2011-03-16
5     2012-03-13
6     2013-03-12
7     2014-03-13
8     2015-03-12
9     2016-03-17
10    2017-03-01
11    2018-02-28
12    2019-02-21
13    2020-02-20
14    2021-02-26
15    2022-03-18
16    2023-02-24
Name: Date, dtype: object

,Date,_cik,_vol,_ret,_vol+1,_ret+1,regional,conserve,stride,genre,...,removed,simulate,touch,licensed,constantly,mode,o,organized,active,necessary
0,2006-03-16,1045810,0.000608,-0.036330,0.000336,0.012794,0.0,0.0,0.0,0.0,...,4.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,10.0
1,2007-03-16,1045810,0.000130,-0.010177,0.000133,-0.000351,0.0,0.0,0.0,0.0,...,4.0,3.0,0.0,3.0,1.0,2.0,0.0,0.0,0.0,12.0
2,2009-03-13,1045810,0.000578,0.009226,0.001266,-0.049700,0.0,0.0,0.0,0.0,...,4.0,3.0,0.0,2.0,1.0,2.0,1.0,0.0,10.0,14.0
3,2010-03-18,1045810,0.000792,-0.037655,0.000653,-0.026882,0.0,0.0,0.0,0.0,...,4.0,3.0,0.0,2.0,1.0,0.0,0.0,0.0,7.0,13.0
4,2011-03-16,1045810,0.001252,0.001713,0.000801,-0.007808,0.0,0.0,0.0,0.0,...,4.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,14.0
5,2012-03-13,1045810,0.000140,0.009511,0.000425,-0.028809,0.0,0.0,0.0,0.0,...,2.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,16.0
6,2013-03-12,1045810,0.000109,0.004721,0.000255,0.000000,0.0,3.0,0.0,0.0,...,0.0,3.0,0.0,2.0,1.0,0.0,0.0,0.0,5.0,14.0
7,2014-03-13,1045810,0.000674,-0.034352,0.000202,0.014698,1.0,3.0,0.0,0.0,...,0.0,3.0,0.0,3.0,1.0,0.0,0.0,0.0,5.0,12.0
8,2015-03-12,1045810,0.000247,0.000441,0.000185,0.006187,2.0,4.0,0.0,0.0,...,1.0,2.0,0.0,5.0,0.0,0.0,0.0,0.0,5.0,7.0
9,2016-03-17,1045810,0.000199,-0.004863,0.000499,0.017906,2.0,0.0,0.0,0.0,...,1.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,8.0
10,2017-03-01,1045810,0.000363,-0.009682,0.000553,-0.032496,2.0,0.0,0.0,0.0,...,1.0,4.0,1.0,3.0,0.0,1.0,0.0,0.0,3.0,8.0
11,2018-02-28,1045810,0.000260,-0.018424,0.001651,-0.040924,2.0,0.0,0.0,0.0,...,1.0,3.0,1.0,3.0,1.0,2.0,0.0,0.0,4.0,6.0
12,2019-02-21,1045810,0.000344,-0.020901,0.000100,0.008390,2.0,0.0,0.0,1.0,...,1.0,3.0,1.0,4.0,1.0,1.0,0.0,0.0,2.0,5.0
13,2020-02-20,1045810,0.001534,-0.013098,0.000859,-0.033835,1.0,0.0,0.0,1.0,...,1.0,3.0,1.0,4.0,1.0,1.0,0.0,0.0,1.0,4.0
14,2021-02-26,1045810,0.000474,-0.002767,0.000264,-0.002399,2.0,0.0,0.0,0.0,...,1.0,2.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0,6.0
15,2022-03-18,1045810,0.002085,0.064566,0.000718,0.008527,2.0,0.0,1.0,0.0,...,1.0,1.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,5.0
16,2023-02-24,1045810,0.000186,0.002623,0.000117,-0.007165,2.0,0.0,0.0,0.0,...,1.0,1.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,6.0

In [55]:

file_path4= "/Users/apple/PROJECT/hons_project/data/SP500/10K/dtm/part-00000-eb3c4dc4-e4b7-4f9a-84c4-9993fc83ba44-c000.snappy.parquet"
df = pd.read_parquet(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
# print(df["Date"])
df.head(100)

(8435, 13687)

,Date,_cik,_vol,_ret,_vol+1,_ret+1,united,state,security,exchange,...,chopped,amalgamate,hala,warden,sanitize,dependably,colossal,crisp,crispy,twister
0,2006-02-15,0000800240,0.000044,-0.027337,0.000698,-0.024406,46.0,54.0,38.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2007-02-14,0000800240,0.000041,-0.021349,0.000127,0.011019,39.0,48.0,39.0,43.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2008-02-26,0000800240,0.000262,-0.041082,0.002024,0.064438,37.0,60.0,53.0,49.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2009-02-24,0000800240,0.006790,-0.051184,0.011989,0.127833,33.0,66.0,48.0,47.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010-02-23,0000800240,0.000294,-0.006448,0.000225,0.010212,33.0,60.0,60.0,66.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2013-02-22,0000820313,0.000022,-0.002886,0.000320,0.028645,17.0,24.0,43.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,2014-02-21,0000820313,0.000020,0.008373,0.000070,-0.004283,15.0,22.0,42.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,2015-02-20,0000820313,0.000054,0.004688,0.000058,0.000529,15.0,19.0,45.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,2016-02-19,0000820313,0.000196,-0.025878,0.000059,-0.000190,19.0,24.0,46.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,2017-02-17,0000820313,0.000034,-0.013034,0.000022,-0.002879,22.0,30.0,51.0,61.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:

file_path4= "/Users/apple/PROJECT/hons_project/data/df_all_0001045810.csv"
df = pd.read_csv(file_path4)

# symbol_data = df[df["symbol"] == "AAPL"]
# Display the data

print(df.shape)
print(df["Date"])
df.head(100)

(17, 3867)
0     2006-03-16
1     2007-03-16
2     2009-03-13
3     2010-03-18
4     2011-03-16
5     2012-03-13
6     2013-03-12
7     2014-03-13
8     2015-03-12
9     2016-03-17
10    2017-03-01
11    2018-02-28
12    2019-02-21
13    2020-02-20
14    2021-02-26
15    2022-03-18
16    2023-02-24
Name: Date, dtype: object

,Unnamed: 0,Date,_cik,_vol,_ret,_vol+1,_ret+1,regional,conserve,stride,...,removed,simulate,touch,licensed,constantly,mode,o,organized,active,necessary
0,0,2006-03-16,1045810,0.000608,-0.036330,0.000336,0.012794,0.0,0.0,0.0,...,4.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,10.0
1,1,2007-03-16,1045810,0.000130,-0.010177,0.000133,-0.000351,0.0,0.0,0.0,...,4.0,3.0,0.0,3.0,1.0,2.0,0.0,0.0,0.0,12.0
2,2,2009-03-13,1045810,0.000578,0.009226,0.001266,-0.049700,0.0,0.0,0.0,...,4.0,3.0,0.0,2.0,1.0,2.0,1.0,0.0,10.0,14.0
3,3,2010-03-18,1045810,0.000792,-0.037655,0.000653,-0.026882,0.0,0.0,0.0,...,4.0,3.0,0.0,2.0,1.0,0.0,0.0,0.0,7.0,13.0
4,4,2011-03-16,1045810,0.001252,0.001713,0.000801,-0.007808,0.0,0.0,0.0,...,4.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,14.0
5,5,2012-03-13,1045810,0.000140,0.009511,0.000425,-0.028809,0.0,0.0,0.0,...,2.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,16.0
6,6,2013-03-12,1045810,0.000109,0.004721,0.000255,0.000000,0.0,3.0,0.0,...,0.0,3.0,0.0,2.0,1.0,0.0,0.0,0.0,5.0,14.0
7,7,2014-03-13,1045810,0.000674,-0.034352,0.000202,0.014698,1.0,3.0,0.0,...,0.0,3.0,0.0,3.0,1.0,0.0,0.0,0.0,5.0,12.0
8,8,2015-03-12,1045810,0.000247,0.000441,0.000185,0.006187,2.0,4.0,0.0,...,1.0,2.0,0.0,5.0,0.0,0.0,0.0,0.0,5.0,7.0
9,9,2016-03-17,1045810,0.000199,-0.004863,0.000499,0.017906,2.0,0.0,0.0,...,1.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,8.0
10,10,2017-03-01,1045810,0.000363,-0.009682,0.000553,-0.032496,2.0,0.0,0.0,...,1.0,4.0,1.0,3.0,0.0,1.0,0.0,0.0,3.0,8.0
11,11,2018-02-28,1045810,0.000260,-0.018424,0.001651,-0.040924,2.0,0.0,0.0,...,1.0,3.0,1.0,3.0,1.0,2.0,0.0,0.0,4.0,6.0
12,12,2019-02-21,1045810,0.000344,-0.020901,0.000100,0.008390,2.0,0.0,0.0,...,1.0,3.0,1.0,4.0,1.0,1.0,0.0,0.0,2.0,5.0
13,13,2020-02-20,1045810,0.001534,-0.013098,0.000859,-0.033835,1.0,0.0,0.0,...,1.0,3.0,1.0,4.0,1.0,1.0,0.0,0.0,1.0,4.0
14,14,2021-02-26,1045810,0.000474,-0.002767,0.000264,-0.002399,2.0,0.0,0.0,...,1.0,2.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0,6.0
15,15,2022-03-18,1045810,0.002085,0.064566,0.000718,0.008527,2.0,0.0,1.0,...,1.0,1.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,5.0
16,16,2023-02-24,1045810,0.000186,0.002623,0.000117,-0.007165,2.0,0.0,0.0,...,1.0,1.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,6.0